version: '3.8'
services:
  app-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  web-viajes:
    image: 'nginx:alpine'
    restart: unless-stopped
    volumes:
      - ./html-viajes:/usr/share/nginx/html
  web-prueba1:
    image: 'nginx:alpine'
    restart: unless-stopped
    volumes:
      - ./html-prueba1:/usr/share/nginx/html

