version: '3.8'
services:
  proxy:
    image: 'nginx:alpine'
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx-ec2.conf:/etc/nginx/conf.d/default.conf
      - ./html-viajes:/usr/share/nginx/html/viajes
      - ./html-prueba1:/usr/share/nginx/html/prueba1
