server {
    listen 80;
    server_name viajes.proyectos.bar;
    root /usr/share/nginx/html/viajes;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name prueba1.proyectos.bar;
    root /usr/share/nginx/html/prueba1;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80 default_server;
    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
    location / {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
